import CashierTemplate from "@/components/cashierTemplate"
import CashierList from "../../cashierList"

export const metadata = {
    title: 'Edukasi | Ordering System',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <CashierTemplate title="Edukasi" id="edukasi" menuList={CashierList}>
            {children}
        </CashierTemplate>
    )
}

export default RootLayout