export const metadata = {
    title: 'User | Ordering System',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <div>
            {children}
        </div>
    )
}


export default RootLayout
